tap "koekeishiya/formulae"
tap "felixkratz/formulae"
tap "nikitabobko/tap"

brew "yabai"
brew "skhd"
brew "sketchybar"
brew "borders"
brew "kitty"
brew "fish"
brew "neovim"
brew "starship"
brew "fastfetch"
brew "btop"
brew "cava"
brew "spicetify-cli"
brew "nowplaying-cli"
brew "switchaudio-osx"

cask "font-jetbrains-mono-nerd-font"
cask "background-music"
cask "blackhole-2ch"
