#!/bin/bash

HOUR=$(date +%H)
INACTIVE_COLOR=0x44ffffff

if [ "$HOUR" -ge 6 ] && [ "$HOUR" -lt 18 ]; then
  ACTIVE_COLOR=0xcce6a050
else
  ACTIVE_COLOR=0xccd45050
fi

/opt/homebrew/bin/borders active_color=$ACTIVE_COLOR \
  inactive_color=$INACTIVE_COLOR \
  width=6.0 \
  hidpi=on \
  style=round \
  &
