gradient_color_1 = '#FF8080'
gradient_color_2 = '#FF8F88'
gradient_color_3 = '#FFA090'
gradient_color_4 = '#FFB098'
gradient_color_5 = '#FFBFA0'
gradient_color_6 = '#FFCFA8'
gradient_color_7 = '#C1D8B5'
gradient_color_8 = '#82D9C2'
