# --- YOUR ORIGINAL COLORS ---
background #0a0a0a
foreground #CCCCCC
cursor #FFCFA8

selection_background #505050
selection_foreground #CCCCCC

color0  #0d0d0d
color1  #FF8080
color2  #82D9C2
color3  #FFCFA8
color4  #8B8B8B
color5  #FFCFA8
color6  #FFCFA8
color7  #FFFFFF
color8  #343434
color9  #FF8080
color10 #82D9C2
color11 #FFCFA8
color12 #8B8B8B
color13 #FFCFA8
color14 #FFCFA8
color15 #FFFFFF

# --- CORE SETTINGS ---
background_opacity 0.8
shell /opt/homebrew/bin/fish

# If Kitty still closes immediately, put a # in front of the next line to test
startup_session ~/.config/kitty/launch.conf

# --- FONT & UI ---
font_size 11
modify_font cell_height 110%

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

window_border_width 0
modify_font baseline 0
draw_minimal_borders yes
window_padding_width 20 25
hide_window_decorations yes
macos_quit_when_last_window_closed yes
confirm_os_window_close 0
macos_traditional_fullscreen no
remember_window_size no
allow_remote_control yes
listen_on unix:/tmp/mykitty
